Repository googleapis/java-resourcemanager, pull requests merged in 2020-09, with the labels that each got.

#225 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: cloudresourcemanager, cla: yes, context: full

#232 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#234 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#247 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#251 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudresourcemanager, automerge, cla: yes

#256 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#258 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
