Repository googleapis/java-resourcemanager, pull requests merged in 2020-06, with the labels that each got.

#171 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#173 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#175 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#177 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#181 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#185 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#189 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#191 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  pom.xml
Labels: cla: yes

#202 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
