Repository googleapis/java-resourcemanager, pull requests merged in 2021-01, with the labels that each got.

#341 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudresourcemanager, cla: yes

#342 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudresourcemanager, automerge, cla: yes

#344 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudresourcemanager, automerge, cla: yes

#347 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudresourcemanager, automerge, cla: yes

#348 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudresourcemanager, automerge, cla: yes

#354 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudresourcemanager, automerge, cla: yes

#357 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudresourcemanager, automerge, cla: yes

#355 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: cloudresourcemanager, automerge, cla: yes, context: full

#358 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: cloudresourcemanager, automerge, cla: yes
